# Generated by Django 6.0.5 on 2026-05-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=52, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='جزئیات')),
                ('status', models.CharField(choices=[('OP', 'باز'), ('CL', 'بسته')], default='OP', max_length=2, verbose_name='وضعیت')),
                ('subject', models.CharField(max_length=2, verbose_name='موضوع')),
            ],
        ),
    ]
