# Generated by Django 6.0.5 on 2026-05-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-name'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=10, verbose_name='موضوع'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-name'], name='post_ticket_name_5fe5cb_idx'),
        ),
    ]
