# Generated by Django 6.0.5 on 2026-05-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_ticket_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام و نام خانوادگی'),
        ),
    ]
