# Generated by Django 6.0.5 on 2026-05-19 15:28

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ انتشار'),
        ),
    ]
