# Generated by Django 6.0.5 on 2026-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created',), 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='post_image_created_0cd738_idx'),
        ),
    ]
