# Generated by Django 6.0.5 on 2026-05-28 08:56

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=80, scale=None, size=[800, 600], upload_to='post_images/<django_jalali.db.models.jDateField>'),
        ),
    ]
