# Generated by Django 6.0.5 on 2026-05-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
    ]
