# Generated by Django 6.0.5 on 2026-06-01 16:34

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import post.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_post_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[800, 600], upload_to=post.models.get_jalali_upload_path),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('bio', models.TextField(max_length=300, verbose_name='بیوگرافی')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[500, 500], upload_to='profile_images')),
                ('job', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب ها',
                'ordering': ('-birth_day_date',),
                'indexes': [models.Index(fields=['-birth_day_date'], name='post_accoun_birth_d_2ec175_idx')],
            },
        ),
    ]
