# Generated by Django 6.0.5 on 2026-06-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_image_image_file_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('تکنولوژی', 'تکنولوژی'), ('برنامه نویسی', 'برنامه نویسی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('بلاکچین', 'بلاکچین'), ('سایر', 'سایر')], default='سایر', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل'),
        ),
    ]
