# Generated by Django 6.0.5 on 2026-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_post_category_alter_account_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('تکنولوژی', 'تکنولوژی'), ('برنامه نویسی', 'برنامه نویسی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('بلاکچین', 'بلاکچین'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
