# Generated by Django 6.0.5 on 2026-06-04 06:33

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth_day_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
